version: "3.7"

services:
  marcosnavarro-web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: nginx
    ports:
      - ${EXTERNAL_PORT}:80
  marcosnavarro-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    command: npm run dev
    volumes:
      - ../:/app